name: RECOVERY

on:
  workflow_dispatch:
    inputs:
      RECOVERY_URL:
        description: 'Recovery image URL (.img or .img.lz4)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            wget \
            git \
            lz4 \
            tar \
            openssl \
            python3 \
            file

      - name: Download latest MagiskBoot
        run: |
          # 1. ดาวน์โหลด Magisk APK เวอร์ชันล่าสุด
          wget -O magisk.apk https://github.com/topjohnwu/Magisk/releases/latest/download/Magisk-v30.7.apk
          
          # 2. แตกไฟล์ดึงเฉพาะ magiskboot (สำหรับคอมพิวเตอร์ x86_64) ออกมา
          # ใน APK ไฟล์นี้จะอยู่ที่ lib/x86_64/libmagiskboot.so
          unzip -j magisk.apk "lib/x86_64/libmagiskboot.so" -d .
          
          # 3. เปลี่ยนชื่อให้เป็น magiskboot แล้วเปิดสิทธิ์ให้สั่งรันได้
          mv libmagiskboot.so magiskboot
          chmod +x magiskboot

      - name: Download latest avbtool
        run: |
          wget -O avbtool https://raw.githubusercontent.com/LineageOS/android_external_avb/refs/heads/lineage-22.1/avbtool
          chmod +x avbtool

      - name: Download recovery
        run: |
          wget "${{ github.event.inputs.RECOVERY_URL }}" -O recovery.img

      - name: Patch Process 1
        run: |
          chmod +x script1.sh
          ./script1.sh recovery.img

      - name: Patch Process 2
        run: |
          chmod +x script2.sh
          ./script2.sh

      - name: Debug
        run: |
          echo "========== FILES =========="
          ls -lah
          find . -name "*.img"

      - name: Sign image
        run: |
          python3 avbtool extract_public_key \
            --key phh.pem \
            --output phh.pub.bin

          SIZE=$(stat -c%s r-patched.img)

          python3 avbtool add_hash_footer \
            --partition_name recovery \
            --partition_size ${SIZE} \
            --image r-patched.img \
            --key phh.pem \
            --algorithm SHA256_RSA4096

      - name: Create Odin package
        run: |
          mkdir output

          mv r-patched.img output/recovery.img

          cd output

          tar --format=ustar -cf recovery.tar recovery.img

          md5sum -t recovery.tar >> recovery.tar

          mv recovery.tar recovery.tar.md5

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Patched-Recovery
          path: output/*

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.run_id }}
          name: Patched-Recovery
          files: output/*
